/**
 * Reference-locked page composition: black-space precision, fine grey rules,
 * high-contrast Domaine display type, ABC Favorit interface copy, and softly
 * rounded product surfaces. Every section corresponds to the supplied Resend
 * reference screenshots; do not reimagine structure, copy, or page rhythm.
 */
import { motion } from "framer-motion";
import HeroCube3D from "@/components/HeroCube3D";
import {
  type LucideIcon,
  Activity,
  ArrowDownToLine,
  Atom,
  BarChart3,
  Beaker,
  Blocks,
  BookOpen,
  Bot,
  Braces,
  Check,
  ChevronDown,
  ChevronRight,
  CircleGauge,
  Clipboard,
  Code2,
  Copy,
  Cpu,
  Download,
  FlaskConical,
  Github,
  Globe2,
  Hand,
  Inbox,
  Languages,
  Link2,
  Mail,
  Monitor,
  Moon,
  Network,
  PackageCheck,
  PanelTop,
  Radar,
  Rocket,
  Send,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Terminal,
  UsersRound,
  Webhook,
  Wifi,
  X,
} from "lucide-react";
import { type ComponentType, useState } from "react";

const MARK = "/manus-storage/resend-clone-mark_105e07a8.png";
const ENVELOPE_TILE = "/manus-storage/resend-clone-envelope-tile_51f62758.png";
const EDITOR_TILE = "/manus-storage/resend-clone-editor-tile_0f74d98b.png";
const REACT_TILE = "/manus-storage/resend-clone-react-tile_963db5d1.png";

const languageTabs: [string, ComponentType<{ size?: number; strokeWidth?: number }>][] = [
  ["Node.js", Braces],
  ["Serverless", ZapMark],
  ["Ruby", GemMark],
  ["Python", Link2],
  ["PHP", Code2],
  ["CLI", Terminal],
  ["Go", GoMark],
  ["Rust", Cpu],
  ["Java", CoffeeMark],
  ["Elixir", DropletMark],
  [".NET", Languages],
  ["REST", Braces],
  ["SMTP", Mail],
];

const frameworkTabs = ["Node.js", "Next.js", "Remix", "Nuxt", "Express", "Hono", "Redwood", "Bun", "Astro"];

const codeByFramework: Record<string, string[]> = {
  "Node.js": [
    "import { Resend } from 'resend';",
    "",
    "const resend = new Resend('re_xxxxxxxxx');",
    "",
    "(async function () {",
    "  const { data, error } = await resend.emails.send({",
    "    from: 'onboarding@resend.dev',",
    "    to: 'delivered@resend.dev',",
    "    subject: 'Hello World',",
    "    html: '<strong>it works!</strong>',",
    "  });",
    "",
    "  if (error) return console.log(error);",
    "  console.log(data);",
    "})();",
  ],
  "Next.js": [
    "import { Resend } from 'resend';",
    "",
    "const resend = new Resend(process.env.RESEND_API_KEY);",
    "",
    "export async function POST() {",
    "  const data = await resend.emails.send({",
    "    from: 'onboarding@resend.dev',",
    "    to: 'delivered@resend.dev',",
    "    subject: 'Hello World',",
    "    html: '<strong>it works!</strong>',",
    "  });",
    "",
    "  return Response.json(data);",
    "}",
  ],
  default: [
    "import { Resend } from 'resend';",
    "",
    "const resend = new Resend('re_xxxxxxxxx');",
    "",
    "const { data, error } = await resend.emails.send({",
    "  from: 'onboarding@resend.dev',",
    "  to: 'delivered@resend.dev',",
    "  subject: 'Hello World',",
    "  html: '<strong>it works!</strong>',",
    "});",
    "",
    "console.log({ data, error });",
  ],
};

const navGroups = ["Features", "Company", "Resources", "Help", "Docs", "AI"];

const deliveryFeatures = [
  { icon: X, title: "Proactive blocklist tracking", copy: "Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend." },
  { icon: Inbox, title: "Faster time to inbox", copy: "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, European, and Asian regions." },
  { icon: Radar, title: "Build confidence with BIMI", copy: "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC - the email equivalent of a checkmark on social media." },
  { icon: Globe2, title: "Managed dedicated IPs", copy: "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period." },
  { icon: Hand, title: "Dynamic suppression list", copy: "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others." },
  { icon: Globe2, title: "IP and domain monitoring", copy: "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability." },
  { icon: Server, title: "Verify DNS records", copy: "Protect your reputation by verifying your identity as a legitimate sender. Secure your email communication using DKIM and SPF." },
  { icon: ShieldCheck, title: "Battle-tested infrastructure", copy: "Rely on a platform of reputable IP's used by trustworthy senders with distributed workloads across different IP pools." },
  { icon: Bot, title: "Prevent spoofing with DMARC", copy: "Avoid impersonation by creating DMARC policies and instructing inbox providers on how to treat unauthenticated email." },
];

const footerColumns = [
  { title: "Features", links: ["Automations", "Audiences", "Broadcasts", "Inbound", "Templates", "Webhooks", "Dedicated IPs"] },
  { title: "Resources", links: ["Changelog", "Pricing", "Enterprise", "Security", "SOC 2", "GDPR", "Brand"] },
  { title: "Company", links: ["About", "Blog", "Careers", "Clubs", "Customers", "Humans", "Philosophy"] },
  { title: "Help", links: ["Contact", "Support", "Status", "Migrate", "Knowledge base", "Legal policies"] },
  { title: "Community", links: ["Events", "Insiders", "Open source", "Wallpapers"] },
];

const fadeUp = {
  initial: { opacity: 0, y: 18 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, amount: 0.2 },
  transition: { duration: 0.54, ease: [0.22, 1, 0.36, 1] as [number, number, number, number] },
};

export default function Home() {
  const [framework, setFramework] = useState("Node.js");
  const [language, setLanguage] = useState("Node.js");
  const [copied, setCopied] = useState(false);
  const [metricTab, setMetricTab] = useState("Intuitive analytics");
  const [sendState, setSendState] = useState<"idle" | "sent">("idle");
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const code = codeByFramework[framework] ?? codeByFramework.default;

  function copyCode() {
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1300);
  }

  return (
    <main className="site-shell">
      <header className="site-nav">
        <a className="wordmark" href="#top" aria-label="Resend home">
          <img className="wordmark-mark" src={MARK} alt="" />
          <span>Resend</span>
        </a>
        <nav className="nav-links" aria-label="Primary navigation">
          {navGroups.map((item) => (
            <div className="nav-menu" key={item} onMouseEnter={() => setOpenMenu(item)} onMouseLeave={() => setOpenMenu(null)}>
              <button type="button" aria-expanded={openMenu === item}>
                {item}<ChevronDown size={13} strokeWidth={1.7} />
              </button>
              <div className={`nav-popover ${openMenu === item ? "is-open" : ""}`}>
                <span>{item} at Resend</span>
                <p>Explore the developer email platform.</p>
              </div>
            </div>
          ))}
          <a href="#pricing">Pricing</a>
        </nav>
        <div className="nav-actions">
          <a className="login-link" href="#login">Log in</a>
          <a className="button button-small" href="#get-started">Get started</a>
        </div>
      </header>

      <section className="hero" id="top">
        <img className="hero-floor" src="/manus-storage/bg-hero-1_70d280af.jpg" alt="" />
        <div className="hero-vignette" />
        <motion.div className="hero-copy" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1, ease: "linear" }}>
          <a className="forward-pill" href="#forward">Join us at Resend Forward <ChevronRight size={14} /></a>
          <h1>Email for<br />developers</h1>
          <p>The best way to reach humans instead of spam folders.<br />Deliver transactional and marketing emails at scale.</p>
          <div className="hero-actions">
            <a className="button" href="#get-started">Get started</a>
            <a className="text-link" href="#docs">Documentation</a>
          </div>
        </motion.div>
        <motion.div className="hero-object" initial={{ opacity: 0, scale: 0.98, x: 22 }} animate={{ opacity: 1, scale: 1, x: 0 }} transition={{ duration: 0.8, delay: 0.18, ease: [0.22, 1, 0.36, 1] as [number, number, number, number] }}>
          <HeroCube3D />
        </motion.div>
      </section>

      <section className="logo-cloud section-rule">
        <img className="light-ray" src="/manus-storage/bg-light_280ddaa3.png" alt="" />
        <motion.p {...fadeUp}>Companies of all sizes trust Resend<br />to deliver their most important emails.</motion.p>
        <motion.div className="logo-grid" {...fadeUp}>
          {["WB WARNER BROS.", "max", "Raycast", "MISTRAL AI_", "replit", "anghami", "gumroad", "DECATHLON", "supabase", "Leap", "Payload", "Paper"].map((logo, index) => <span className={`logo-company logo-${index}`} key={logo}>{logo}</span>)}
        </motion.div>
      </section>

      <section className="section integration-section" id="docs">
        <motion.div className="centre-heading" {...fadeUp}>
          <img src={ENVELOPE_TILE} className="feature-tile" alt="" />
          <h2>Integrate <span className="spectrum-text">this weekend</span></h2>
          <p>A simple, elegant interface so you can start sending emails in minutes. It fits<br />right into your code with SDKs for your favorite programming languages.</p>
        </motion.div>
        <div className="language-tabs" role="tablist" aria-label="SDK languages">
          {languageTabs.map(([label, Icon]) => (
            <button className={`sdk-choice ${language === label ? "active" : ""}`} onClick={() => setLanguage(label)} type="button" role="tab" aria-selected={language === label} key={label}>
              <span className="sdk-icon"><Icon size={23} strokeWidth={1.8} /></span><span>{label}</span>
            </button>
          ))}
        </div>
        <motion.div className="code-window" {...fadeUp}>
          <div className="code-window-tabs">
            <div className="framework-tabs" role="tablist">
              {frameworkTabs.map((tab) => <button type="button" role="tab" onClick={() => setFramework(tab)} aria-selected={framework === tab} className={framework === tab ? "active" : ""} key={tab}>{tab}</button>)}
            </div>
            <button onClick={copyCode} className="icon-button" type="button" aria-label="Copy code">{copied ? <Check size={17} /> : <Copy size={17} />}</button>
          </div>
          <pre>{code.map((line, index) => <code key={`${framework}-${index}`}><span className="line-number">{index + 1}</span>{highlightCode(line)}</code>)}</pre>
          <div className="code-bottom-links"><a href="#github"><Github size={16} /> View on GitHub</a><a href="#zip"><Download size={16} /> Download ZIP</a></div>
        </motion.div>
      </section>

      <section className="section developer-section">
        <div className="editorial-heading">
          <motion.div {...fadeUp}><h2>First-class<br />developer experience</h2><p>We are a team of engineers who love building tools for other engineers.<br />Our goal is to create the email platform we've always wished we had — one that <em>just works.</em></p></motion.div>
        </div>
        <div className="dual-product-grid">
          <motion.article className="product-card test-card" {...fadeUp}>
            <div className="test-console">
              <div className="test-toolbar"><span className={`status-chip ${sendState === "sent" ? "sent" : ""}`}>{sendState === "sent" ? "Sent" : "Delivered"}</span><span>delivered@resend.dev <ChevronDown size={13} /></span><button type="button" onClick={() => setSendState("sent")}><Beaker size={14} /> {sendState === "sent" ? "Sent" : "Send"}</button></div>
              <div className="console-lines">{["acd15abb-8495-44ef-8491-f3812861c298", "311e1193-6c08-4af4-b1c3-75ce08173d7d", "3e10e70f-5b36-46f2-be39-ed36a9ee424f", "80b74db8-f2f0-48bb-8f12-52fe4363968b"].map((id) => <p key={id}>HTTP 200: <span>{'{ "id": "'}{id}{'" }'}</span></p>)}</div>
            </div>
            <FeatureCaption icon={FlaskConical} title="Test mode" copy="Simulate events and experiment with our API without the risk of accidentally sending real emails to real people." />
          </motion.article>
          <motion.article className="product-card webhook-card" {...fadeUp}>
            <div className="event-timeline">
              {[{ state: "Clicked", color: "purple", from: "isabella@yahoo.com", agent: "Yahoo Mail", platform: "Windows" }, { state: "Opened", color: "blue", from: "noah@figma.com", agent: "Super Mail", platform: "Windows" }].map((event, index) => <div className="event-item" key={event.state}><div className="event-node"><Send size={19} /></div>{index === 0 && <div className="event-line" />}<div className="event-content"><div><b className={`event-label ${event.color}`}>{event.state}</b><span className="event-time">◷ Aug 22&nbsp; 06:2{8 - index}:0{7 - index * 5}</span></div><p>from <strong>{event.from}</strong> on <strong>Get Started</strong></p><p>on agent <strong>{event.agent}</strong> running on <strong>{event.platform}</strong></p></div></div>)}
            </div>
            <FeatureCaption icon={Webhook} title="Modular webhooks" copy="Receive real-time notifications directly to your server. Every time an email is delivered, opened, bounces, or a link is clicked." />
          </motion.article>
        </div>
      </section>

      <section className="section centred-product-section">
        <motion.div className="centre-heading" {...fadeUp}>
          <img src={EDITOR_TILE} className="feature-tile" alt="" />
          <h2>Write using a delightful editor</h2>
          <p>A modern editor that makes it easy for anyone to write, format, and send emails.<br />Visually build your email and change the design by adding custom styles.</p>
        </motion.div>
        <motion.div className="editor-demo" {...fadeUp}>
          <div className="editor-topline"><button type="button"><Sparkles size={17} /> Styles</button><strong>Weekly Acme Newsletter</strong><div><span>◷&nbsp; a day ago</span><button type="button">Test</button><button className="editor-send" type="button">Send</button></div></div>
          <div className="editor-message"><p><span>From</span><b>your.name@acme.com</b></p><p><span>To</span><b className="recipient"><UsersRound size={15} /> Newsletter Subscribers</b></p><p><span>Subject</span><b>Weekly Newsletter</b></p><img src="/manus-storage/broadcast-email-header_9491a1e4.jpg" alt="" /></div>
        </motion.div>
      </section>

      <section className="section beyond-editing-section">
        <motion.div className="editorial-heading" {...fadeUp}><h2>Go beyond editing</h2><p>Group and control your contacts in a simple and intuitive way.<br />Straightforward analytics and reporting tools that will help you send better emails.</p></motion.div>
        <div className="image-feature-grid">
          <motion.article className="visual-card" {...fadeUp}><img src="/manus-storage/screenshot-zoom-audience_24a264c7.png" alt="Audience interface" /><FeatureCaption icon={UsersRound} title="Contact management" copy="Import your list in minutes, regardless the size of your audience. Get full visibility of each contact and their personal attributes." /></motion.article>
          <motion.article className="visual-card" {...fadeUp}><img src="/manus-storage/screenshot-zoom-analytics_362794c2.png" alt="Analytics interface" /><FeatureCaption icon={BarChart3} title="Broadcast analytics" copy="Unlock powerful insights and understand exactly how your audience is interacting with your broadcast emails." /></motion.article>
        </div>
      </section>

      <section className="section centred-product-section react-section">
        <motion.div className="centre-heading" {...fadeUp}>
          <img src={REACT_TILE} className="feature-tile" alt="" />
          <h2>Develop emails using React</h2>
          <p>Create beautiful templates without having to deal with &lt;table&gt; layouts and HTML.<br />Powered by react-email, our open source component library.</p>
          <div className="hero-actions centred-actions"><a className="button" href="#get-started">Get started <ChevronRight size={15} /></a><a className="text-link" href="#check-docs">Check the docs <ChevronRight size={15} /></a></div>
        </motion.div>
        <motion.div className="react-code-window" {...fadeUp}><div className="window-bar"><span className="window-dots"><i /><i /><i /></span><div className="window-tools"><Monitor size={16} /><Moon size={16} /></div></div><div className="template-tabs"><span className="active">user-welcome.tsx</span><span>reset-password.tsx</span><span>user-invite.tsx</span><span>weekly-digest.tsx</span></div><div className="react-code"><span>1</span><p><b>import</b> {'{ Body, Button, Column, Container, Head, Heading, Hr, Html, Img, Link }'} <b>from</b> <em>'react-email'</em>;</p></div></motion.div>
      </section>

      <section className="section deliverability-section">
        <motion.div className="editorial-heading" {...fadeUp}><h2>Reach humans, not<br />spam folders</h2></motion.div>
        <div className="benefit-grid">{deliveryFeatures.map(({ icon: Icon, title, copy }) => <motion.article key={title} className="benefit-card" {...fadeUp}><Icon size={22} strokeWidth={1.8} /><h3>{title}</h3><p>{copy}</p></motion.article>)}</div>
        <motion.blockquote className="quote-feature" {...fadeUp}><div className="vercel-mark">▲</div><p>Resend is transforming email for developers.<br />Simple interface, easy integrations, handy<br />templates. What else could we ask for.</p><footer><span className="avatar avatar-guillermo" /> <span><b>Guillermo Rauch</b><small>CEO at Vercel</small></span></footer></motion.blockquote>
      </section>

      <section className="section control-section">
        <motion.div className="centre-heading" {...fadeUp}><div className="control-orb"><Globe2 size={58} strokeWidth={1.1} /></div><h2>Everything in your control</h2><p>All the features you need to manage your email sending, troubleshoot with<br />detailed logs, and protect your domain reputation – without the friction.</p></motion.div>
        <div className="control-tabs" role="tablist">{([ ["Intuitive analytics", BarChart3], ["Full visibility", Mail], ["Domain authentication", Globe2] ] as [string, LucideIcon][]).map(([label, Icon]) => <button type="button" role="tab" aria-selected={metricTab === label} className={metricTab === label ? "active" : ""} onClick={() => setMetricTab(label)} key={label}><span className="tab-glow" aria-hidden="true" /><span className="tab-mask" aria-hidden="true" /><span className="tab-content"><span className="tab-icon"><Icon size={20} /></span>{label}</span></button>)}</div>
        <motion.div className="metrics-frame" {...fadeUp}><img src="/manus-storage/screenshot-metrics_95f656ab.png" alt="Resend dashboard metrics" /></motion.div>
      </section>

      <section className="section expectation-section">
        <motion.div className="centre-heading" {...fadeUp}><h2>Beyond expectations</h2><p>Resend is driving remarkable developer experiences that enable success<br />stories, empower businesses, and fuel growth across industries and individuals.</p></motion.div>
        <div className="testimonial-grid">
          <QuoteCard quote="Our partnership with Resend has been a great experience. They've made sure we can focus on what we do best—building our product and growing our business." name="Sahil Lavingia" role="CEO of Gumroad" initials="G" />
          <QuoteCard quote="Switching over to Resend from SendGrid marked a significant improvement in our email management. We started with a small test - waitlist emails for our iOS and Windows apps. Within 30 minutes, we were done." name="Thomas Mann" role="Founder & CEO of Raycast" initials="R" />
          <QuoteCard quote="The simplicity and reliability of Resend allowed our engineers to focus on building features rather than troubleshooting email infrastructure." name="Amadeo Pellicce" role="Connectors, Agents and Automations Lead at Replit" initials="r" />
        </div>
      </section>

      <footer className="site-footer">
        <div className="footer-watermark">RESEND</div>
        <div className="footer-main">
          <div className="footer-intro"><a className="wordmark footer-wordmark" href="#top"><img className="wordmark-mark" src={MARK} alt="" /><span>Resend</span></a><p>2261 Market Street #5039<br />San Francisco, CA 94114</p><div className="socials"><a href="#x">𝕏</a><a href="#github"><Github size={17} /></a><a href="#linkedin">in</a><a href="#youtube">▶</a></div><span className="system-status"><i /> All systems operational</span></div>
          <div className="footer-links">{footerColumns.map((column) => <section key={column.title}><h3>{column.title}</h3>{column.links.map(link => <a href={`#${link.toLowerCase().replaceAll(" ", "-")}`} key={link}>{link}</a>)}</section>)}</div>
        </div>
      </footer>
    </main>
  );
}

function FeatureCaption({ icon: Icon, title, copy }: { icon: typeof Mail; title: string; copy: string }) {
  return <div className="feature-caption"><Icon size={23} strokeWidth={1.8} /><h3>{title}</h3><p>{copy}</p><a href="#learn-more">Learn more <ChevronRight size={14} /></a></div>;
}

function QuoteCard({ quote, name, role, initials }: { quote: string; name: string; role: string; initials: string }) {
  return <motion.article className="quote-card" {...fadeUp}><p>“{quote}”</p><footer><span className="avatar">{initials}</span><span><b>{name}</b><small>{role}</small></span></footer></motion.article>;
}

function highlightCode(line: string) {
  if (!line) return " ";
  const marked = line.replace(/(import|from|const|async|function|await|return|if|console)/g, "§$1§").split("§");
  return marked.map((part, index) => index % 2 ? <span className="code-keyword" key={`${part}-${index}`}>{part}</span> : part);
}

function ZapMark({ size = 23 }: { size?: number }) { return <span className="glyph-mark" style={{ fontSize: size }}>ϟ</span>; }
function GemMark({ size = 23 }: { size?: number }) { return <span className="glyph-mark" style={{ fontSize: size - 3 }}>◇</span>; }
function GoMark({ size = 23 }: { size?: number }) { return <span className="glyph-mark glyph-go" style={{ fontSize: size - 7 }}>GO</span>; }
function CoffeeMark({ size = 23 }: { size?: number }) { return <span className="glyph-mark" style={{ fontSize: size - 2 }}>♨</span>; }
function DropletMark({ size = 23 }: { size?: number }) { return <span className="glyph-mark" style={{ fontSize: size - 1 }}>♢</span>; }
